/** Códigos de error de negocio y su mensaje para el usuario final. */
export const ErrorCode = {
  SLOT_TAKEN: 'SLOT_TAKEN',
  OUTSIDE_AVAILABILITY: 'OUTSIDE_AVAILABILITY',
  SLOT_IN_PAST: 'SLOT_IN_PAST',
  ACTIVE_LIMIT: 'ACTIVE_LIMIT',
  PATIENT_SLOT_CONFLICT: 'PATIENT_SLOT_CONFLICT',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  CONCURRENT_UPDATE: 'CONCURRENT_UPDATE',
  AVAILABILITY_IN_USE: 'AVAILABILITY_IN_USE',
  FOLLOW_UP_NOT_ALLOWED: 'FOLLOW_UP_NOT_ALLOWED',
  NO_DOCTOR: 'NO_DOCTOR',
  VALIDATION: 'VALIDATION',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DOMAIN_NOT_ALLOWED: 'DOMAIN_NOT_ALLOWED',
  EMAIL_NOT_ALLOWED: 'EMAIL_NOT_ALLOWED',
  USER_INACTIVE: 'USER_INACTIVE',
  CSRF: 'CSRF',
  RATE_LIMIT: 'RATE_LIMIT',
  INTERNAL: 'INTERNAL',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  SLOT_TAKEN: 'El horario seleccionado acaba de ser reservado por otro usuario. Por favor, selecciona otro horario.',
  OUTSIDE_AVAILABILITY: 'El horario seleccionado no pertenece a la disponibilidad configurada.',
  SLOT_IN_PAST: 'El horario seleccionado ya no está disponible para reservas.',
  ACTIVE_LIMIT: 'Ya tienes el máximo de citas activas permitidas. Podrás reservar otra cuando finalice tu cita actual; si necesitas cambiarla o cancelarla, comunícate con el consultorio.',
  PATIENT_SLOT_CONFLICT: 'El paciente ya tiene otra cita en ese horario.',
  INVALID_TRANSITION: 'La cita no se encuentra en un estado que permita esta acción.',
  CONCURRENT_UPDATE: 'La cita fue modificada por otra persona. Actualiza la página e inténtalo de nuevo.',
  AVAILABILITY_IN_USE: 'El cambio dejaría citas reservadas fuera de la disponibilidad. Reprograma o cancela esas citas primero.',
  FOLLOW_UP_NOT_ALLOWED: 'Solo se puede crear una cita de seguimiento desde una atención en proceso o finalizada.',
  NO_DOCTOR: 'No hay un doctor configurado en el sistema.',
  VALIDATION: 'Los datos enviados no son válidos.',
  NOT_FOUND: 'El recurso solicitado no existe.',
  FORBIDDEN: 'No tienes permisos para realizar esta acción.',
  UNAUTHORIZED: 'Tu sesión expiró. Inicia sesión nuevamente.',
  DOMAIN_NOT_ALLOWED: 'Tu cuenta de correo no pertenece a un dominio autorizado para usar este sistema.',
  EMAIL_NOT_ALLOWED: 'Tu cuenta no tiene acceso a este sistema. Las cuentas estudiantiles no están habilitadas.',
  USER_INACTIVE: 'Tu cuenta está desactivada. Contacta al administrador.',
  CSRF: 'La solicitud no pudo ser verificada. Recarga la página e inténtalo de nuevo.',
  RATE_LIMIT: 'Demasiadas solicitudes. Espera un momento e inténtalo de nuevo.',
  INTERNAL: 'Ocurrió un error inesperado. Inténtalo de nuevo.',
};
